module.exports = {
  bindedFiles: {
    clusterIP: '172.30.211.216',
    username: 'hippo',
    user: 'hippo',
    uri: 'postgresql://hippo:n%5BgGI-lYrF%29%29Xg%3FYD85%5E%29%5B%3A%7D@hippo-primary.postgres-operator.svc:5432/hippo',
    type: 'postgresql',
    sslkey: `-----BEGIN EC PRIVATE KEY-----
MHcCAQEEICk4mszncScy73aH1ka9QYYvI1ke8pJCsKMfVIZxBFNToAoGCCqGSM49
AwEHoUQDQgAExD0YjN0MDCrQwBhLxEUQ3F+x0YHx3ZL5ZZtp6thule0d/f/s4+Tc
nyQm0sNzqY4kCQW/2m3n6EKNKUosnDzK0A==
-----END EC PRIVATE KEY-----`,
    sslcert: `-----BEGIN CERTIFICATE-----
MIIBjjCCATWgAwIBAgIRAMY+fouG11/LsCYFIbQ8ciswCgYIKoZIzj0EAwMwHzEd
MBsGA1UEAxMUcG9zdGdyZXMtb3BlcmF0b3ItY2EwHhcNMjIwNTA2MTAyMTIwWhcN
MjMwNTA2MTEyMTIwWjAXMRUwEwYDVQQDDAxfY3J1bmNoeXJlcGwwWTATBgcqhkjO
PQIBBggqhkjOPQMBBwNCAATEPRiM3QwMKtDAGEvERRDcX7HRgfHdkvllm2nq2G6V
7R39/+zj5NyfJCbSw3OpjiQJBb/abefoQo0pSiycPMrQo1owWDAOBgNVHQ8BAf8E
BAMCBaAwDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAWgBTdQTGKlE2udoxqL5y0MRSL
xxLZ7jAXBgNVHREEEDAOggxfY3J1bmNoeXJlcGwwCgYIKoZIzj0EAwMDRwAwRAIg
HQm3Ishta7p6RO7G67WXxBxnHmtKuRTlzFxKrNhUiUQCIHpeFAcklDEYyXP+zzMx
mArNG3Notbl85/dwYhWzRafC
-----END CERTIFICATE-----`,
    'root.key': `-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIDW4yyG3ZgPkEJmDyOZHdKvlqyXAi9Hj/BYpMZS+AoQMoAoGCCqGSM49
AwEHoUQDQgAEbIWW6CllscGy3/MV86WCnE9q4RVGLOiWt4sR9qOJJOvtyK75n6pu
o373zR0fll5fsjqY9a9r/a5hwEAZMXaG6A==
-----END EC PRIVATE KEY-----`,
    'root.crt': `-----BEGIN CERTIFICATE-----
MIIBgjCCASegAwIBAgIQHeIPKnEo+f4McKfie8hc0DAKBggqhkjOPQQDAzAfMR0w
GwYDVQQDExRwb3N0Z3Jlcy1vcGVyYXRvci1jYTAeFw0yMjA1MDYxMDIxMTlaFw0z
MjA1MDMxMTIxMTlaMB8xHTAbBgNVBAMTFHBvc3RncmVzLW9wZXJhdG9yLWNhMFkw
EwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEbIWW6CllscGy3/MV86WCnE9q4RVGLOiW
t4sR9qOJJOvtyK75n6puo373zR0fll5fsjqY9a9r/a5hwEAZMXaG6KNFMEMwDgYD
VR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFN1BMYqU
Ta52jGovnLQxFIvHEtnuMAoGCCqGSM49BAMDA0kAMEYCIQDwWbjPh72wnfDI9+Fj
j3pc35wtJKhLg7ZcAqa0jTnGIgIhAL1i0vZvJQvFBVvCdy2R3qFftzp2gMtzvFWy
tl+vsM2Z
-----END CERTIFICATE-----`,
    provider: 'crunchydata',
    port: '5432',
    'pgbackrest.ca-roots': `-----BEGIN CERTIFICATE-----
MIIBgjCCASegAwIBAgIQHeIPKnEo+f4McKfie8hc0DAKBggqhkjOPQQDAzAfMR0w
GwYDVQQDExRwb3N0Z3Jlcy1vcGVyYXRvci1jYTAeFw0yMjA1MDYxMDIxMTlaFw0z
MjA1MDMxMTIxMTlaMB8xHTAbBgNVBAMTFHBvc3RncmVzLW9wZXJhdG9yLWNhMFkw
EwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEbIWW6CllscGy3/MV86WCnE9q4RVGLOiW
t4sR9qOJJOvtyK75n6puo373zR0fll5fsjqY9a9r/a5hwEAZMXaG6KNFMEMwDgYD
VR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFN1BMYqU
Ta52jGovnLQxFIvHEtnuMAoGCCqGSM49BAMDA0kAMEYCIQDwWbjPh72wnfDI9+Fj
j3pc35wtJKhLg7ZcAqa0jTnGIgIhAL1i0vZvJQvFBVvCdy2R3qFftzp2gMtzvFWy
tl+vsM2Z
-----END CERTIFICATE-----`,
    'pgbackrest-server.crt': `-----BEGIN CERTIFICATE-----
MIICmjCCAkGgAwIBAgIRAPmTvS8j6FV3fLyxUiNOikUwCgYIKoZIzj0EAwMwHzEd
MBsGA1UEAxMUcG9zdGdyZXMtb3BlcmF0b3ItY2EwHhcNMjIwNTEzMTIxMTI0WhcN
MjMwNTEzMTMxMTI0WjBRMU8wTQYDVQQDE0ZoaXBwby1pbnN0YW5jZTEtbmxqOC0w
LmhpcHBvLXBvZHMucG9zdGdyZXMtb3BlcmF0b3Iuc3ZjLmNsdXN0ZXIubG9jYWwu
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEvTGCPHbU02Vve8MoC72hGbz0o9J2
zIS+dMKC1Ym+PIMg5h6lZpz+4p2TLXsolcqz0t5HnusZWFqdMm5drraRXKOCASow
ggEmMA4GA1UdDwEB/wQEAwIFoDAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFHVe
2Xoi+MjQOiUbXRSUhFMCgK8jMIHkBgNVHREEgdwwgdmCRmhpcHBvLWluc3RhbmNl
MS1ubGo4LTAuaGlwcG8tcG9kcy5wb3N0Z3Jlcy1vcGVyYXRvci5zdmMuY2x1c3Rl
ci5sb2NhbC6CN2hpcHBvLWluc3RhbmNlMS1ubGo4LTAuaGlwcG8tcG9kcy5wb3N0
Z3Jlcy1vcGVyYXRvci5zdmOCM2hpcHBvLWluc3RhbmNlMS1ubGo4LTAuaGlwcG8t
cG9kcy5wb3N0Z3Jlcy1vcGVyYXRvcoIhaGlwcG8taW5zdGFuY2UxLW5sajgtMC5o
aXBwby1wb2RzMAoGCCqGSM49BAMDA0cAMEQCIHec7D3txYmYT5nDVtT2k1beOpxV
cWJpwJ7jFqeMXIKPAiBoT96H28PW6K4Iy2640FSgI1TtVbEukWYaAzLnNFbN8w==
-----END CERTIFICATE-----`,
    'pgbackrest-server.key': `-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIB/L+mq95eoc+BM+lvBZMqYhZCZT0kdKazk+JMBkz9choAoGCCqGSM49
AwEHoUQDQgAEZECmRQWxx1TGS8TQ4qxPsnf51XXTHEp6PhfoIV28nxDQruzqUy8C
4LjcifgJo4oW4/1RnBFdrBqA9WyedeC+VQ==
-----END EC PRIVATE KEY-----`,
    'pgbackrest-server.conf': `# Generated by postgres-operator. DO NOT EDIT.
# Your changes will not be saved.

[global]
tls-server-address = 0.0.0.0
tls-server-auth = pgbackrest@e1df7693-093c-41d4-9d1f-24726c8c7e7d=*
tls-server-ca-file = /etc/pgbackrest/conf.d/~postgres-operator/tls-ca.crt
tls-server-cert-file = /etc/pgbackrest/server/server-tls.crt
tls-server-key-file = /etc/pgbackrest/server/server-tls.key

[global:server]
log-level-console = detail
log-level-file = off
log-level-stderr = error
log-timestamp = n`,
    'pgbackrest-repo-host.key': `-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIGtZm6UT6YJcV1Je4Bna+dlXOUfsONrF7R/klAtAHUkuoAoGCCqGSM49
AwEHoUQDQgAEWwJ+P4CqWIcnp84MatCYI8N1bUPl7Se8+spN8rqxWzvFNlY881r0
p+ocSYInf6ldfAffALDlzrMZQKyQCjccKg==
-----END EC PRIVATE KEY-----`,
    'pgbackrest-repo-host.crt': `-----BEGIN CERTIFICATE-----
MIICgDCCAiegAwIBAgIQarGTjePzmuyE31e41fycxTAKBggqhkjOPQQDAzAfMR0w
GwYDVQQDExRwb3N0Z3Jlcy1vcGVyYXRvci1jYTAeFw0yMjA1MTMxMjExMjRaFw0y
MzA1MTMxMzExMjRaMEwxSjBIBgNVBAMTQWhpcHBvLXJlcG8taG9zdC0wLmhpcHBv
LXBvZHMucG9zdGdyZXMtb3BlcmF0b3Iuc3ZjLmNsdXN0ZXIubG9jYWwuMFkwEwYH
KoZIzj0CAQYIKoZIzj0DAQcDQgAEqFdQy7lZ3Od4Y6RZ0/Tk3YZcl2oNJC1epbxD
KsM5bKB7bfFHFFFex7sq8jrF53ClIqkpKTdJJeLS6I5nWr96NqOCARYwggESMA4G
A1UdDwEB/wQEAwIFoDAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFHVe2Xoi+MjQ
OiUbXRSUhFMCgK8jMIHQBgNVHREEgcgwgcWCQWhpcHBvLXJlcG8taG9zdC0wLmhp
cHBvLXBvZHMucG9zdGdyZXMtb3BlcmF0b3Iuc3ZjLmNsdXN0ZXIubG9jYWwugjJo
aXBwby1yZXBvLWhvc3QtMC5oaXBwby1wb2RzLnBvc3RncmVzLW9wZXJhdG9yLnN2
Y4IuaGlwcG8tcmVwby1ob3N0LTAuaGlwcG8tcG9kcy5wb3N0Z3Jlcy1vcGVyYXRv
coIcaGlwcG8tcmVwby1ob3N0LTAuaGlwcG8tcG9kczAKBggqhkjOPQQDAwNHADBE
AiB1Y9+rm+/LSZo5z6BIL4wpv+IgizN9lLGRTzFrI/kBSwIgWNkUfbWNVLXxphrt
wYp+gKEmkqBXnwrOuO6WH5MX/2E=
-----END CERTIFICATE-----`,
    'pgbackrest-client.key': `-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIPYa8XwmhI+0vrg5/6JpkqaiStjb+G7LWMZ2w/Fb5/QboAoGCCqGSM49
AwEHoUQDQgAEPWsPlZ7BUBi1M1n3f74wRAfvRYPYqOCN+vtt1V99B2rfyFsuBA7t
L5m/HerfyWChbnGGZvnbY5+V8p0Rf/UO3A==
-----END EC PRIVATE KEY-----`,
    'pgbackrest-client.crt': `-----BEGIN CERTIFICATE-----
MIIB0zCCAXqgAwIBAgIQc9CLyDUEqN0bdure/SwsQTAKBggqhkjOPQQDAzAfMR0w
GwYDVQQDExRwb3N0Z3Jlcy1vcGVyYXRvci1jYTAeFw0yMjA1MDYxMDIxMjBaFw0y
MzA1MDYxMTIxMjBaMDoxODA2BgNVBAMML3BnYmFja3Jlc3RAZTFkZjc2OTMtMDkz
Yy00MWQ0LTlkMWYtMjQ3MjZjOGM3ZTdkMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcD
QgAEPWsPlZ7BUBi1M1n3f74wRAfvRYPYqOCN+vtt1V99B2rfyFsuBA7tL5m/Herf
yWChbnGGZvnbY5+V8p0Rf/UO3KN9MHswDgYDVR0PAQH/BAQDAgWgMAwGA1UdEwEB
/wQCMAAwHwYDVR0jBBgwFoAU3UExipRNrnaMai+ctDEUi8cS2e4wOgYDVR0RBDMw
MYIvcGdiYWNrcmVzdEBlMWRmNzY5My0wOTNjLTQxZDQtOWQxZi0yNDcyNmM4Yzdl
N2QwCgYIKoZIzj0EAwMDRwAwRAIgQ5rVhlBXq68ke1rlv5U0shU4u0D1F8vKn5DW
4nFM1yoCIG8P0bvObkqA+S8oAbGU2lRb5MXvnGHwmRCZVkO2yhto
-----END CERTIFICATE-----`,
    'pgbackrest_repo.conf': `# Generated by postgres-operator. DO NOT EDIT.
# Your changes will not be saved.

[global]
log-path = /pgbackrest/repo1/log
repo1-path = /pgbackrest/repo1

[db]
pg1-host = hippo-instance1-87wl-0.hippo-pods.postgres-operator.svc.cluster.local.
pg1-host-ca-file = /etc/pgbackrest/conf.d/~postgres-operator/tls-ca.crt
pg1-host-cert-file = /etc/pgbackrest/conf.d/~postgres-operator/client-tls.crt
pg1-host-key-file = /etc/pgbackrest/conf.d/~postgres-operator/client-tls.key
pg1-host-type = tls
pg1-path = /pgdata/pg14
pg1-port = 5432
pg1-socket-path = /tmp/postgres`,
    'pgbackrest_instance.conf': `# Generated by postgres-operator. DO NOT EDIT.
# Your changes will not be saved.

[global]
log-path = /pgdata/pgbackrest/log
repo1-host = hippo-repo-host-0.hippo-pods.postgres-operator.svc.cluster.local.
repo1-host-ca-file = /etc/pgbackrest/conf.d/~postgres-operator/tls-ca.crt
repo1-host-cert-file = /etc/pgbackrest/conf.d/~postgres-operator/client-tls.crt
repo1-host-key-file = /etc/pgbackrest/conf.d/~postgres-operator/client-tls.key
repo1-host-type = tls
repo1-host-user = postgres
repo1-path = /pgbackrest/repo1

[db]
pg1-path = /pgdata/pg14
pg1-port = 5432
pg1-socket-path = /tmp/postgres`,
    'patroni.yaml': `# Generated by postgres-operator. DO NOT EDIT`,
    'patroni.crt-combined': `-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIB/L+mq95eoc+BM+lvBZMqYhZCZT0kdKazk+JMBkz9choAoGCCqGSM49
AwEHoUQDQgAEZECmRQWxx1TGS8TQ4qxPsnf51XXTHEp6PhfoIV28nxDQruzqUy8C
4LjcifgJo4oW4/1RnBFdrBqA9WyedeC+VQ==
-----END EC PRIVATE KEY-----
-----BEGIN CERTIFICATE-----
MIICmzCCAkCgAwIBAgIQWXISg/dNQBvWy6vsnULt/zAKBggqhkjOPQQDAzAfMR0w
GwYDVQQDExRwb3N0Z3Jlcy1vcGVyYXRvci1jYTAeFw0yMjA1MjYxMTI1NTJaFw0y
MzA1MjYxMjI1NTJaMFExTzBNBgNVBAMTRmhpcHBvLWluc3RhbmNlMS00ZGg4LTAu
aGlwcG8tcG9kcy5wb3N0Z3Jlcy1vcGVyYXRvci5zdmMuY2x1c3Rlci5sb2NhbC4w
WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARkQKZFBbHHVMZLxNDirE+yd/nVddMc
Sno+F+ghXbyfENCu7OpTLwLguNyJ+Amjihbj/VGcEV2sGoD1bJ514L5Vo4IBKjCC
ASYwDgYDVR0PAQH/BAQDAgWgMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUpvfn
NjprTjhP7qpiUTqUfLcr34gwgeQGA1UdEQSB3DCB2YJGaGlwcG8taW5zdGFuY2Ux
LTRkaDgtMC5oaXBwby1wb2RzLnBvc3RncmVzLW9wZXJhdG9yLnN2Yy5jbHVzdGVy
LmxvY2FsLoI3aGlwcG8taW5zdGFuY2UxLTRkaDgtMC5oaXBwby1wb2RzLnBvc3Rn
cmVzLW9wZXJhdG9yLnN2Y4IzaGlwcG8taW5zdGFuY2UxLTRkaDgtMC5oaXBwby1w
b2RzLnBvc3RncmVzLW9wZXJhdG9ygiFoaXBwby1pbnN0YW5jZTEtNGRoOC0wLmhp
cHBvLXBvZHMwCgYIKoZIzj0EAwMDSQAwRgIhAKFAk3AR/2pjcYwgyJA4aoGqK8jL
c7Jexl9TWNXUAx2aAiEA1p/x4xaurYgQuEcxYAQpL4MoGb6+I0QS1GSy0qWuLVk=
-----END CERTIFICATE-----`,
    'patroni.ca-roots': `-----BEGIN CERTIFICATE-----
MIIBgjCCASegAwIBAgIQHeIPKnEo+f4McKfie8hc0DAKBggqhkjOPQQDAzAfMR0w
GwYDVQQDExRwb3N0Z3Jlcy1vcGVyYXRvci1jYTAeFw0yMjA1MDYxMDIxMTlaFw0z
MjA1MDMxMTIxMTlaMB8xHTAbBgNVBAMTFHBvc3RncmVzLW9wZXJhdG9yLWNhMFkw
EwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEbIWW6CllscGy3/MV86WCnE9q4RVGLOiW
t4sR9qOJJOvtyK75n6puo373zR0fll5fsjqY9a9r/a5hwEAZMXaG6KNFMEMwDgYD
VR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFN1BMYqU
Ta52jGovnLQxFIvHEtnuMAoGCCqGSM49BAMDA0kAMEYCIQDwWbjPh72wnfDI9+Fj
j3pc35wtJKhLg7ZcAqa0jTnGIgIhAL1i0vZvJQvFBVvCdy2R3qFftzp2gMtzvFWy
tl+vsM2Z
-----END CERTIFICATE-----`,
    password: `n[gGI-lYrF))Xg?YD85^)[:}`,
    'jdbc-uri': `jdbc:postgresql://hippo-primary.postgres-operator.svc:5432/hippo?password=n%5BgGI-lYrF%29%29Xg%3FYD85%5E%29%5B%3A%7D&user=hippo`,
    host: 'hippo-primary.postgres-operator.svc',
    'dns.key': `-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIM6uEXMf11D3Dh/8dQ37r692vlwcgXwYNBrQ+8BNYHudoAoGCCqGSM49
AwEHoUQDQgAETI37Rg4KrEsRLdoj37YrI8sxnyenTXdelYRKhvJdPU8m+lh6LMNP
iyqzasFe20SC0OHHFlfN3asI909pbTjMEw==
-----END EC PRIVATE KEY-----`,
    'dns.crt': `-----BEGIN CERTIFICATE-----
MIICmjCCAkCgAwIBAgIQFSvhiRg/D2lhyBXiztSKGTAKBggqhkjOPQQDAzAfMR0w
GwYDVQQDExRwb3N0Z3Jlcy1vcGVyYXRvci1jYTAeFw0yMjA1MDYxMDIxMjBaFw0y
MzA1MDYxMTIxMjBaMFExTzBNBgNVBAMTRmhpcHBvLWluc3RhbmNlMS04N3dsLTAu
aGlwcG8tcG9kcy5wb3N0Z3Jlcy1vcGVyYXRvci5zdmMuY2x1c3Rlci5sb2NhbC4w
WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARMjftGDgqsSxEt2iPftisjyzGfJ6dN
d16VhEqG8l09Tyb6WHosw0+LKrNqwV7bRILQ4ccWV83dqwj3T2ltOMwTo4IBKjCC
ASYwDgYDVR0PAQH/BAQDAgWgMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAU3UEx
ipRNrnaMai+ctDEUi8cS2e4wgeQGA1UdEQSB3DCB2YJGaGlwcG8taW5zdGFuY2Ux
LTg3d2wtMC5oaXBwby1wb2RzLnBvc3RncmVzLW9wZXJhdG9yLnN2Yy5jbHVzdGVy
LmxvY2FsLoI3aGlwcG8taW5zdGFuY2UxLTg3d2wtMC5oaXBwby1wb2RzLnBvc3Rn
cmVzLW9wZXJhdG9yLnN2Y4IzaGlwcG8taW5zdGFuY2UxLTg3d2wtMC5oaXBwby1w
b2RzLnBvc3RncmVzLW9wZXJhdG9ygiFoaXBwby1pbnN0YW5jZTEtODd3bC0wLmhp
cHBvLXBvZHMwCgYIKoZIzj0EAwMDSAAwRQIhAKU2AJj8Ca0Wi/V9zONIXm+Wu7hu
B70+jPy77U8m5LUOAiALzKdUq8zPDlLeIlS4Bq2eTbe0Iouc9mMszcFFzO4vEg==
-----END CERTIFICATE-----`,
    dbname: 'hippo',
    database: 'hippo',
    'config-hash': '65bb57b6b5',
    verifier:
      'SCRAM-SHA-256$4096:5iwkKQp8vScS+FelWG4sqg==$UdLEmGRCM44fHUVnwq9vPC1Zk/0eRABJP8OGyaNKWJE=:6Zcv32v7WwXKAisWUs7JYv/uh6nclf1LA6voZKbJCjk='
  },
  connectionString: `DRIVER=PostgreSQL;Servername=hippo-primary.postgres-operator.svc;DATABASE=hippo;Port=5432;Username=hippo;Password=n[gGI-lYrF))Xg?YD85^)[:};SSLmode=verify-full`
};
