const crunchyDB = {
  clusterIP: '172.30.211.216',
  'config-hash': '65bb57b6b5',
  database: 'hippo',
  dbname: 'hippo',
  'dns.crt':
    '-----BEGIN CERTIFICATE-----\nMIICmjCCAkCgAwIBAgIQFSvhiRg/D2lhyBXiztSKGTAKBggqhkjOPQQDAzAfMR0w\nGwYDVQQDExRwb3N0Z3Jlcy1vcGVyYXRvci1jYTAeFw0yMjA1MDYxMDIxMjBaFw0y\nMzA1MDYxMTIxMjBaMFExTzBNBgNVBAMTRmhpcHBvLWluc3RhbmNlMS04N3dsLTAu\naGlwcG8tcG9kcy5wb3N0Z3Jlcy1vcGVyYXRvci5zdmMuY2x1c3Rlci5sb2NhbC4w\nWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARMjftGDgqsSxEt2iPftisjyzGfJ6dN\nd16VhEqG8l09Tyb6WHosw0+LKrNqwV7bRILQ4ccWV83dqwj3T2ltOMwTo4IBKjCC\nASYwDgYDVR0PAQH/BAQDAgWgMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAU3UEx\nipRNrnaMai+ctDEUi8cS2e4wgeQGA1UdEQSB3DCB2YJGaGlwcG8taW5zdGFuY2Ux\nLTg3d2wtMC5oaXBwby1wb2RzLnBvc3RncmVzLW9wZXJhdG9yLnN2Yy5jbHVzdGVy\nLmxvY2FsLoI3aGlwcG8taW5zdGFuY2UxLTg3d2wtMC5oaXBwby1wb2RzLnBvc3Rn\ncmVzLW9wZXJhdG9yLnN2Y4IzaGlwcG8taW5zdGFuY2UxLTg3d2wtMC5oaXBwby1w\nb2RzLnBvc3RncmVzLW9wZXJhdG9ygiFoaXBwby1pbnN0YW5jZTEtODd3bC0wLmhp\ncHBvLXBvZHMwCgYIKoZIzj0EAwMDSAAwRQIhAKU2AJj8Ca0Wi/V9zONIXm+Wu7hu\nB70+jPy77U8m5LUOAiALzKdUq8zPDlLeIlS4Bq2eTbe0Iouc9mMszcFFzO4vEg==\n-----END CERTIFICATE-----',
  'dns.key':
    '-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIM6uEXMf11D3Dh/8dQ37r692vlwcgXwYNBrQ+8BNYHudoAoGCCqGSM49\nAwEHoUQDQgAETI37Rg4KrEsRLdoj37YrI8sxnyenTXdelYRKhvJdPU8m+lh6LMNP\niyqzasFe20SC0OHHFlfN3asI909pbTjMEw==\n-----END EC PRIVATE KEY-----',
  host: 'hippo-primary.postgres-operator.svc',
  'jdbc-uri':
    'jdbc:postgresql://hippo-primary.postgres-operator.svc:5432/hippo?password=n%5BgGI-lYrF%29%29Xg%3FYD85%5E%29%5B%3A%7D&user=hippo',
  password: 'n[gGI-lYrF))Xg?YD85^)[:}',
  'patroni.ca-roots':
    '-----BEGIN CERTIFICATE-----\nMIIBgjCCASegAwIBAgIQHeIPKnEo+f4McKfie8hc0DAKBggqhkjOPQQDAzAfMR0w\nGwYDVQQDExRwb3N0Z3Jlcy1vcGVyYXRvci1jYTAeFw0yMjA1MDYxMDIxMTlaFw0z\nMjA1MDMxMTIxMTlaMB8xHTAbBgNVBAMTFHBvc3RncmVzLW9wZXJhdG9yLWNhMFkw\nEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEbIWW6CllscGy3/MV86WCnE9q4RVGLOiW\nt4sR9qOJJOvtyK75n6puo373zR0fll5fsjqY9a9r/a5hwEAZMXaG6KNFMEMwDgYD\nVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFN1BMYqU\nTa52jGovnLQxFIvHEtnuMAoGCCqGSM49BAMDA0kAMEYCIQDwWbjPh72wnfDI9+Fj\nj3pc35wtJKhLg7ZcAqa0jTnGIgIhAL1i0vZvJQvFBVvCdy2R3qFftzp2gMtzvFWy\ntl+vsM2Z\n-----END CERTIFICATE-----',
  'patroni.crt-combined':
    '-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIB/L+mq95eoc+BM+lvBZMqYhZCZT0kdKazk+JMBkz9choAoGCCqGSM49\nAwEHoUQDQgAEZECmRQWxx1TGS8TQ4qxPsnf51XXTHEp6PhfoIV28nxDQruzqUy8C\n4LjcifgJo4oW4/1RnBFdrBqA9WyedeC+VQ==\n-----END EC PRIVATE KEY-----\n-----BEGIN CERTIFICATE-----\nMIICmzCCAkCgAwIBAgIQWXISg/dNQBvWy6vsnULt/zAKBggqhkjOPQQDAzAfMR0w\nGwYDVQQDExRwb3N0Z3Jlcy1vcGVyYXRvci1jYTAeFw0yMjA1MjYxMTI1NTJaFw0y\nMzA1MjYxMjI1NTJaMFExTzBNBgNVBAMTRmhpcHBvLWluc3RhbmNlMS00ZGg4LTAu\naGlwcG8tcG9kcy5wb3N0Z3Jlcy1vcGVyYXRvci5zdmMuY2x1c3Rlci5sb2NhbC4w\nWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARkQKZFBbHHVMZLxNDirE+yd/nVddMc\nSno+F+ghXbyfENCu7OpTLwLguNyJ+Amjihbj/VGcEV2sGoD1bJ514L5Vo4IBKjCC\nASYwDgYDVR0PAQH/BAQDAgWgMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUpvfn\nNjprTjhP7qpiUTqUfLcr34gwgeQGA1UdEQSB3DCB2YJGaGlwcG8taW5zdGFuY2Ux\nLTRkaDgtMC5oaXBwby1wb2RzLnBvc3RncmVzLW9wZXJhdG9yLnN2Yy5jbHVzdGVy\nLmxvY2FsLoI3aGlwcG8taW5zdGFuY2UxLTRkaDgtMC5oaXBwby1wb2RzLnBvc3Rn\ncmVzLW9wZXJhdG9yLnN2Y4IzaGlwcG8taW5zdGFuY2UxLTRkaDgtMC5oaXBwby1w\nb2RzLnBvc3RncmVzLW9wZXJhdG9ygiFoaXBwby1pbnN0YW5jZTEtNGRoOC0wLmhp\ncHBvLXBvZHMwCgYIKoZIzj0EAwMDSQAwRgIhAKFAk3AR/2pjcYwgyJA4aoGqK8jL\nc7Jexl9TWNXUAx2aAiEA1p/x4xaurYgQuEcxYAQpL4MoGb6+I0QS1GSy0qWuLVk=\n-----END CERTIFICATE-----',
  'patroni.yaml': '# Generated by postgres-operator. DO NOT EDIT',
  'pgbackrest-client.crt':
    '-----BEGIN CERTIFICATE-----\nMIIB0zCCAXqgAwIBAgIQc9CLyDUEqN0bdure/SwsQTAKBggqhkjOPQQDAzAfMR0w\nGwYDVQQDExRwb3N0Z3Jlcy1vcGVyYXRvci1jYTAeFw0yMjA1MDYxMDIxMjBaFw0y\nMzA1MDYxMTIxMjBaMDoxODA2BgNVBAMML3BnYmFja3Jlc3RAZTFkZjc2OTMtMDkz\nYy00MWQ0LTlkMWYtMjQ3MjZjOGM3ZTdkMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcD\nQgAEPWsPlZ7BUBi1M1n3f74wRAfvRYPYqOCN+vtt1V99B2rfyFsuBA7tL5m/Herf\nyWChbnGGZvnbY5+V8p0Rf/UO3KN9MHswDgYDVR0PAQH/BAQDAgWgMAwGA1UdEwEB\n/wQCMAAwHwYDVR0jBBgwFoAU3UExipRNrnaMai+ctDEUi8cS2e4wOgYDVR0RBDMw\nMYIvcGdiYWNrcmVzdEBlMWRmNzY5My0wOTNjLTQxZDQtOWQxZi0yNDcyNmM4Yzdl\nN2QwCgYIKoZIzj0EAwMDRwAwRAIgQ5rVhlBXq68ke1rlv5U0shU4u0D1F8vKn5DW\n4nFM1yoCIG8P0bvObkqA+S8oAbGU2lRb5MXvnGHwmRCZVkO2yhto\n-----END CERTIFICATE-----',
  'pgbackrest-client.key':
    '-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIPYa8XwmhI+0vrg5/6JpkqaiStjb+G7LWMZ2w/Fb5/QboAoGCCqGSM49\nAwEHoUQDQgAEPWsPlZ7BUBi1M1n3f74wRAfvRYPYqOCN+vtt1V99B2rfyFsuBA7t\nL5m/HerfyWChbnGGZvnbY5+V8p0Rf/UO3A==\n-----END EC PRIVATE KEY-----',
  'pgbackrest-repo-host.crt':
    '-----BEGIN CERTIFICATE-----\nMIICgDCCAiegAwIBAgIQarGTjePzmuyE31e41fycxTAKBggqhkjOPQQDAzAfMR0w\nGwYDVQQDExRwb3N0Z3Jlcy1vcGVyYXRvci1jYTAeFw0yMjA1MTMxMjExMjRaFw0y\nMzA1MTMxMzExMjRaMEwxSjBIBgNVBAMTQWhpcHBvLXJlcG8taG9zdC0wLmhpcHBv\nLXBvZHMucG9zdGdyZXMtb3BlcmF0b3Iuc3ZjLmNsdXN0ZXIubG9jYWwuMFkwEwYH\nKoZIzj0CAQYIKoZIzj0DAQcDQgAEqFdQy7lZ3Od4Y6RZ0/Tk3YZcl2oNJC1epbxD\nKsM5bKB7bfFHFFFex7sq8jrF53ClIqkpKTdJJeLS6I5nWr96NqOCARYwggESMA4G\nA1UdDwEB/wQEAwIFoDAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFHVe2Xoi+MjQ\nOiUbXRSUhFMCgK8jMIHQBgNVHREEgcgwgcWCQWhpcHBvLXJlcG8taG9zdC0wLmhp\ncHBvLXBvZHMucG9zdGdyZXMtb3BlcmF0b3Iuc3ZjLmNsdXN0ZXIubG9jYWwugjJo\naXBwby1yZXBvLWhvc3QtMC5oaXBwby1wb2RzLnBvc3RncmVzLW9wZXJhdG9yLnN2\nY4IuaGlwcG8tcmVwby1ob3N0LTAuaGlwcG8tcG9kcy5wb3N0Z3Jlcy1vcGVyYXRv\ncoIcaGlwcG8tcmVwby1ob3N0LTAuaGlwcG8tcG9kczAKBggqhkjOPQQDAwNHADBE\nAiB1Y9+rm+/LSZo5z6BIL4wpv+IgizN9lLGRTzFrI/kBSwIgWNkUfbWNVLXxphrt\nwYp+gKEmkqBXnwrOuO6WH5MX/2E=\n-----END CERTIFICATE-----',
  'pgbackrest-repo-host.key':
    '-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIGtZm6UT6YJcV1Je4Bna+dlXOUfsONrF7R/klAtAHUkuoAoGCCqGSM49\nAwEHoUQDQgAEWwJ+P4CqWIcnp84MatCYI8N1bUPl7Se8+spN8rqxWzvFNlY881r0\np+ocSYInf6ldfAffALDlzrMZQKyQCjccKg==\n-----END EC PRIVATE KEY-----',
  'pgbackrest-server.conf':
    '# Generated by postgres-operator. DO NOT EDIT.\n# Your changes will not be saved.\n\n[global]\ntls-server-address = 0.0.0.0\ntls-server-auth = pgbackrest@e1df7693-093c-41d4-9d1f-24726c8c7e7d=*\ntls-server-ca-file = /etc/pgbackrest/conf.d/~postgres-operator/tls-ca.crt\ntls-server-cert-file = /etc/pgbackrest/server/server-tls.crt\ntls-server-key-file = /etc/pgbackrest/server/server-tls.key\n\n[global:server]\nlog-level-console = detail\nlog-level-file = off\nlog-level-stderr = error\nlog-timestamp = n',
  'pgbackrest-server.crt':
    '-----BEGIN CERTIFICATE-----\nMIICmjCCAkGgAwIBAgIRAPmTvS8j6FV3fLyxUiNOikUwCgYIKoZIzj0EAwMwHzEd\nMBsGA1UEAxMUcG9zdGdyZXMtb3BlcmF0b3ItY2EwHhcNMjIwNTEzMTIxMTI0WhcN\nMjMwNTEzMTMxMTI0WjBRMU8wTQYDVQQDE0ZoaXBwby1pbnN0YW5jZTEtbmxqOC0w\nLmhpcHBvLXBvZHMucG9zdGdyZXMtb3BlcmF0b3Iuc3ZjLmNsdXN0ZXIubG9jYWwu\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEvTGCPHbU02Vve8MoC72hGbz0o9J2\nzIS+dMKC1Ym+PIMg5h6lZpz+4p2TLXsolcqz0t5HnusZWFqdMm5drraRXKOCASow\nggEmMA4GA1UdDwEB/wQEAwIFoDAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFHVe\n2Xoi+MjQOiUbXRSUhFMCgK8jMIHkBgNVHREEgdwwgdmCRmhpcHBvLWluc3RhbmNl\nMS1ubGo4LTAuaGlwcG8tcG9kcy5wb3N0Z3Jlcy1vcGVyYXRvci5zdmMuY2x1c3Rl\nci5sb2NhbC6CN2hpcHBvLWluc3RhbmNlMS1ubGo4LTAuaGlwcG8tcG9kcy5wb3N0\nZ3Jlcy1vcGVyYXRvci5zdmOCM2hpcHBvLWluc3RhbmNlMS1ubGo4LTAuaGlwcG8t\ncG9kcy5wb3N0Z3Jlcy1vcGVyYXRvcoIhaGlwcG8taW5zdGFuY2UxLW5sajgtMC5o\naXBwby1wb2RzMAoGCCqGSM49BAMDA0cAMEQCIHec7D3txYmYT5nDVtT2k1beOpxV\ncWJpwJ7jFqeMXIKPAiBoT96H28PW6K4Iy2640FSgI1TtVbEukWYaAzLnNFbN8w==\n-----END CERTIFICATE-----',
  'pgbackrest-server.key':
    '-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIB/L+mq95eoc+BM+lvBZMqYhZCZT0kdKazk+JMBkz9choAoGCCqGSM49\nAwEHoUQDQgAEZECmRQWxx1TGS8TQ4qxPsnf51XXTHEp6PhfoIV28nxDQruzqUy8C\n4LjcifgJo4oW4/1RnBFdrBqA9WyedeC+VQ==\n-----END EC PRIVATE KEY-----',
  'pgbackrest.ca-roots':
    '-----BEGIN CERTIFICATE-----\nMIIBgjCCASegAwIBAgIQHeIPKnEo+f4McKfie8hc0DAKBggqhkjOPQQDAzAfMR0w\nGwYDVQQDExRwb3N0Z3Jlcy1vcGVyYXRvci1jYTAeFw0yMjA1MDYxMDIxMTlaFw0z\nMjA1MDMxMTIxMTlaMB8xHTAbBgNVBAMTFHBvc3RncmVzLW9wZXJhdG9yLWNhMFkw\nEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEbIWW6CllscGy3/MV86WCnE9q4RVGLOiW\nt4sR9qOJJOvtyK75n6puo373zR0fll5fsjqY9a9r/a5hwEAZMXaG6KNFMEMwDgYD\nVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFN1BMYqU\nTa52jGovnLQxFIvHEtnuMAoGCCqGSM49BAMDA0kAMEYCIQDwWbjPh72wnfDI9+Fj\nj3pc35wtJKhLg7ZcAqa0jTnGIgIhAL1i0vZvJQvFBVvCdy2R3qFftzp2gMtzvFWy\ntl+vsM2Z\n-----END CERTIFICATE-----',
  'pgbackrest_instance.conf':
    '# Generated by postgres-operator. DO NOT EDIT.\n# Your changes will not be saved.\n\n[global]\nlog-path = /pgdata/pgbackrest/log\nrepo1-host = hippo-repo-host-0.hippo-pods.postgres-operator.svc.cluster.local.\nrepo1-host-ca-file = /etc/pgbackrest/conf.d/~postgres-operator/tls-ca.crt\nrepo1-host-cert-file = /etc/pgbackrest/conf.d/~postgres-operator/client-tls.crt\nrepo1-host-key-file = /etc/pgbackrest/conf.d/~postgres-operator/client-tls.key\nrepo1-host-type = tls\nrepo1-host-user = postgres\nrepo1-path = /pgbackrest/repo1\n\n[db]\npg1-path = /pgdata/pg14\npg1-port = 5432\npg1-socket-path = /tmp/postgres',
  'pgbackrest_repo.conf':
    '# Generated by postgres-operator. DO NOT EDIT.\n# Your changes will not be saved.\n\n[global]\nlog-path = /pgbackrest/repo1/log\nrepo1-path = /pgbackrest/repo1\n\n[db]\npg1-host = hippo-instance1-87wl-0.hippo-pods.postgres-operator.svc.cluster.local.\npg1-host-ca-file = /etc/pgbackrest/conf.d/~postgres-operator/tls-ca.crt\npg1-host-cert-file = /etc/pgbackrest/conf.d/~postgres-operator/client-tls.crt\npg1-host-key-file = /etc/pgbackrest/conf.d/~postgres-operator/client-tls.key\npg1-host-type = tls\npg1-path = /pgdata/pg14\npg1-port = 5432\npg1-socket-path = /tmp/postgres',
  port: '5432',
  provider: 'crunchydata',
  'ca.crt':
    '-----BEGIN CERTIFICATE-----\nMIIBgjCCASegAwIBAgIQHeIPKnEo+f4McKfie8hc0DAKBggqhkjOPQQDAzAfMR0w\nGwYDVQQDExRwb3N0Z3Jlcy1vcGVyYXRvci1jYTAeFw0yMjA1MDYxMDIxMTlaFw0z\nMjA1MDMxMTIxMTlaMB8xHTAbBgNVBAMTFHBvc3RncmVzLW9wZXJhdG9yLWNhMFkw\nEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEbIWW6CllscGy3/MV86WCnE9q4RVGLOiW\nt4sR9qOJJOvtyK75n6puo373zR0fll5fsjqY9a9r/a5hwEAZMXaG6KNFMEMwDgYD\nVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFN1BMYqU\nTa52jGovnLQxFIvHEtnuMAoGCCqGSM49BAMDA0kAMEYCIQDwWbjPh72wnfDI9+Fj\nj3pc35wtJKhLg7ZcAqa0jTnGIgIhAL1i0vZvJQvFBVvCdy2R3qFftzp2gMtzvFWy\ntl+vsM2Z\n-----END CERTIFICATE-----',
  'root.crt':
    '-----BEGIN CERTIFICATE-----\nMIIBgjCCASegAwIBAgIQHeIPKnEo+f4McKfie8hc0DAKBggqhkjOPQQDAzAfMR0w\nGwYDVQQDExRwb3N0Z3Jlcy1vcGVyYXRvci1jYTAeFw0yMjA1MDYxMDIxMTlaFw0z\nMjA1MDMxMTIxMTlaMB8xHTAbBgNVBAMTFHBvc3RncmVzLW9wZXJhdG9yLWNhMFkw\nEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEbIWW6CllscGy3/MV86WCnE9q4RVGLOiW\nt4sR9qOJJOvtyK75n6puo373zR0fll5fsjqY9a9r/a5hwEAZMXaG6KNFMEMwDgYD\nVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFN1BMYqU\nTa52jGovnLQxFIvHEtnuMAoGCCqGSM49BAMDA0kAMEYCIQDwWbjPh72wnfDI9+Fj\nj3pc35wtJKhLg7ZcAqa0jTnGIgIhAL1i0vZvJQvFBVvCdy2R3qFftzp2gMtzvFWy\ntl+vsM2Z\n-----END CERTIFICATE-----',
  'root.key':
    '-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIDW4yyG3ZgPkEJmDyOZHdKvlqyXAi9Hj/BYpMZS+AoQMoAoGCCqGSM49\nAwEHoUQDQgAEbIWW6CllscGy3/MV86WCnE9q4RVGLOiWt4sR9qOJJOvtyK75n6pu\no373zR0fll5fsjqY9a9r/a5hwEAZMXaG6A==\n-----END EC PRIVATE KEY-----',
  type: 'postgresql',
  uri: 'postgresql://hippo:n%5BgGI-lYrF%29%29Xg%3FYD85%5E%29%5B%3A%7D@hippo-primary.postgres-operator.svc:5432/hippo',
  user: 'hippo',
  verifier:
    'SCRAM-SHA-256$4096:5iwkKQp8vScS+FelWG4sqg==$UdLEmGRCM44fHUVnwq9vPC1Zk/0eRABJP8OGyaNKWJE=:6Zcv32v7WwXKAisWUs7JYv/uh6nclf1LA6voZKbJCjk='
};

const crunchyDataBindingsMappedForPG = (function () {
  const { 'root.crt': rootCrt, ...rest } = crunchyDB;
  return {
    ...rest,
    ssl: {
      ca: '-----BEGIN CERTIFICATE-----\nMIIBgjCCASegAwIBAgIQHeIPKnEo+f4McKfie8hc0DAKBggqhkjOPQQDAzAfMR0w\nGwYDVQQDExRwb3N0Z3Jlcy1vcGVyYXRvci1jYTAeFw0yMjA1MDYxMDIxMTlaFw0z\nMjA1MDMxMTIxMTlaMB8xHTAbBgNVBAMTFHBvc3RncmVzLW9wZXJhdG9yLWNhMFkw\nEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEbIWW6CllscGy3/MV86WCnE9q4RVGLOiW\nt4sR9qOJJOvtyK75n6puo373zR0fll5fsjqY9a9r/a5hwEAZMXaG6KNFMEMwDgYD\nVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFN1BMYqU\nTa52jGovnLQxFIvHEtnuMAoGCCqGSM49BAMDA0kAMEYCIQDwWbjPh72wnfDI9+Fj\nj3pc35wtJKhLg7ZcAqa0jTnGIgIhAL1i0vZvJQvFBVvCdy2R3qFftzp2gMtzvFWy\ntl+vsM2Z\n-----END CERTIFICATE-----',
      cert: '-----BEGIN CERTIFICATE-----\nMIIBjjCCATWgAwIBAgIRAMY+fouG11/LsCYFIbQ8ciswCgYIKoZIzj0EAwMwHzEd\nMBsGA1UEAxMUcG9zdGdyZXMtb3BlcmF0b3ItY2EwHhcNMjIwNTA2MTAyMTIwWhcN\nMjMwNTA2MTEyMTIwWjAXMRUwEwYDVQQDDAxfY3J1bmNoeXJlcGwwWTATBgcqhkjO\nPQIBBggqhkjOPQMBBwNCAATEPRiM3QwMKtDAGEvERRDcX7HRgfHdkvllm2nq2G6V\n7R39/+zj5NyfJCbSw3OpjiQJBb/abefoQo0pSiycPMrQo1owWDAOBgNVHQ8BAf8E\nBAMCBaAwDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAWgBTdQTGKlE2udoxqL5y0MRSL\nxxLZ7jAXBgNVHREEEDAOggxfY3J1bmNoeXJlcGwwCgYIKoZIzj0EAwMDRwAwRAIg\nHQm3Ishta7p6RO7G67WXxBxnHmtKuRTlzFxKrNhUiUQCIHpeFAcklDEYyXP+zzMx\nmArNG3Notbl85/dwYhWzRafC\n-----END CERTIFICATE-----',
      key: '-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEICk4mszncScy73aH1ka9QYYvI1ke8pJCsKMfVIZxBFNToAoGCCqGSM49\nAwEHoUQDQgAExD0YjN0MDCrQwBhLxEUQ3F+x0YHx3ZL5ZZtp6thule0d/f/s4+Tc\nnyQm0sNzqY4kCQW/2m3n6EKNKUosnDzK0A==\n-----END EC PRIVATE KEY-----'
    }
  };
})();

const postgresqlDBRHODA = {
  ssl: {
    ca: '----BEGIN CERTIFICATE-----\nKLMN\n-----END CERTIFICATE-----'
  },
  database: 'db1',
  host: '127.0.0.1',
  password: 'p1',
  port: '1234',
  options: '--cluster=fruit-service-test -c opt1=val1',
  sslmode: 'verify-full',
  sslrootcert: 'root.crt',
  type: 'postgresql',
  user: 'fruit-user',
  provider: 'CockroachDB Cloud'
};

const postgresqlDBRHODAOPT = {
  database: 'db1',
  host: '127.0.0.1',
  password: 'p1',
  port: '1234',
  options: '--cluster=fruit-service-test -c opt2=val2',
  type: 'postgresql',
  user: 'fruit-user',
  provider: 'CockroachDB Cloud'
};

const crunchyDataBindingsMappedForOdbc = (function () {
  const { 'ca.crt': caCrt, ...rest } = crunchyDB;
  return {
    ...rest,
    username: 'hippo'
  };
})();

const postgresDataBindingsMappedForPGRHODA = {
  ...postgresqlDBRHODA
};

const postgresDataBindingsMappedForPGRHODAOPT = {
  ...postgresqlDBRHODAOPT
};

function getPqopt({ serviceBindingRoot, overrideSslkeyPath }) {
  let sslkeyPath = `${serviceBindingRoot}/crunchy-data-postgres-operator/tls.key`;
  if (overrideSslkeyPath) {
    sslkeyPath = `${overrideSslkeyPath}`;
  }

  return [
    '{',
    `sslrootcert=${serviceBindingRoot}/crunchy-data-postgres-operator/ca.crt`,
    `sslcert=${serviceBindingRoot}/crunchy-data-postgres-operator/tls.crt`,
    `sslkey=${sslkeyPath}`,
    '}'
  ].join(' ');
}

function getSslcerts({ serviceBindingRoot, overrideSslkeyPath }) {
  let sslkeyPath = `${serviceBindingRoot}/crunchy-data-postgres-operator/tls.key`;
  if (overrideSslkeyPath) {
    sslkeyPath = `${overrideSslkeyPath}`;
  }

  return {
    sslrootcert: `${serviceBindingRoot}/crunchy-data-postgres-operator/ca.crt`,
    sslcert: `${serviceBindingRoot}/crunchy-data-postgres-operator/tls.crt`,
    sslkey: `${sslkeyPath}`
  };
}

function getOdbcConnectionString(pqopt) {
  const connectionOptions = [
    'DRIVER=PostgreSQL;',
    'Servername=hippo-primary.postgres-operator.svc;',
    'DATABASE=hippo;Port=5432;Username=hippo;',
    'Password=n[gGI-lYrF))Xg?YD85^)[:};',
    'SSLmode=verify-full'
  ].join('');
  return { connectionString: `Pqopt=${pqopt};${connectionOptions}` };
}

module.exports = {
  crunchyDB,
  crunchyDataBindingsMappedForPG,
  crunchyDataBindingsMappedForOdbc,
  postgresDataBindingsMappedForPGRHODA,
  postgresDataBindingsMappedForPGRHODAOPT,
  getPqopt,
  getSslcerts,
  getOdbcConnectionString
};
